optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.001, 
    weight_decay: 0.0005
  }
}

scheduler: {
  type: LambdaLR,
  kwargs: {
    decay_step: 21,
    lr_decay: 0.92596,
    lowest_decay: 0.001
  }
}

bnmscheduler: {
  type: Lambda,
  kwargs: {
    decay_step: 21,
    bn_decay: 0.5,
    bn_momentum: 0.9,
    lowest_decay: 0.01
  }
}

dataset: {
  train: { 
    _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
    others: {subset: 'train'}
  },
  val: { 
    _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
    others: {subset: 'test'}
  },
  test: { 
    _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
    others: {subset: 'test'}
  }
}

model: {
  NAME: SnowFlakeNet,
  dim_feat: 512,
  num_pc: 256,
  num_p0: 512,
  radius: 1,
  up_factors: [4, 8]
}

total_bs: 16
step_per_update: 4
max_epoch: 200
consider_metric: CDL2